packages:
  - 'packages/*'
catalog:
  '@emotion/native': '~11.11.0'
  '@emotion/react': '~11.11.0'
  '@emotion/styled': '~11.11.0'
  clsx: '2.1.1'
  currency.js: '~2.0.4'
  react-international-phone: '^4.6.1'
  react-native-vector-icons: '^9.2.0'
  tailwind-variants: '3.3.0'
  tailwindcss: '^4.1.16'
allowBuilds:
  '@swc/core': true
  core-js-pure: true
  esbuild: true
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@storybook/addon-ondevice-actions@10.5.4'
  - '@storybook/addon-ondevice-backgrounds@10.5.4'
  - '@storybook/addon-ondevice-controls@10.5.4'
  - '@storybook/react-native-theming@10.5.4'
  - '@storybook/react-native-ui-common@10.5.4'
  - '@storybook/react-native-ui@10.5.4'
  - '@storybook/react-native@10.5.4'
nodeLinker: hoisted
