/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './packages/react-web-kit/src/components/atoms/**/*.{js,ts,jsx,tsx}',
    './packages/cortex-core/docs/*.{js,ts,jsx,tsx}',
    './packages/cortex-react/docs/*.{js,ts,jsx,tsx}',
    './docs/**/*.{js,ts,jsx,tsx}',
    './packages/cortex-core/src/components/**/*.{js,ts,jsx,tsx}',
    './packages/cortex-react/src/**/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          xlight: 'var(--color-primary-xlight)',
          light: 'var(--color-primary-light)',
          medium: 'var(--color-primary-medium)',
          dark: 'var(--color-primary-dark)',
          xdark: 'var(--color-primary-xdark)',
        },
        secondary: {
          xlight: 'var(--color-secondary-xlight)',
          light: 'var(--color-secondary-light)',
          medium: 'var(--color-secondary-medium)',
          dark: 'var(--color-secondary-dark)',
          xdark: 'var(--color-secondary-xdark)',
        },
        info: {
          xlight: 'var(--color-info-xlight)',
          light: 'var(--color-info-light)',
          medium: 'var(--color-info-medium)',
          dark: 'var(--color-info-dark)',
          xdark: 'var(--color-info-xdark)',
        },
        success: {
          xlight: 'var(--color-success-xlight)',
          light: 'var(--color-success-light)',
          medium: 'var(--color-success-medium)',
          dark: 'var(--color-success-dark)',
          xdark: 'var(--color-success-xdark)',
        },
        warning: {
          xlight: 'var(--color-warning-xlight)',
          light: 'var(--color-warning-light)',
          medium: 'var(--color-warning-medium)',
          dark: 'var(--color-warning-dark)',
          xdark: 'var(--color-warning-xdark)',
        },
        error: {
          xlight: 'var(--color-error-xlight)',
          light: 'var(--color-error-light)',
          medium: 'var(--color-error-medium)',
          dark: 'var(--color-error-dark)',
          xdark: 'var(--color-error-xdark)',
        },
        miscellaneous: {
          body: 'var(--color-miscellaneous-body)',
        },
      },
      spacing: {
        nano: 'var(--spacing-nano)',
        micro: 'var(--spacing-micro)',
        mili: 'var(--spacing-mili)',
        centi: 'var(--spacing-centi)',
        deca: 'var(--spacing-deca)',
        kilo: 'var(--spacing-kilo)',
        mega: 'var(--spacing-mega)',
        giga: 'var(--spacing-giga)',
        tera: 'var(--spacing-tera)',
        peta: 'var(--spacing-peta)',
        hexa: 'var(--spacing-hexa)',
      },
      borderRadius: {
        nano: 'var(--border-radius-nano)',
        micro: 'var(--border-radius-micro)',
        mili: 'var(--border-radius-mili)',
        centi: 'var(--border-radius-centi)',
        deca: 'var(--border-radius-deca)',
        pill: 'var(--border-radius-pill)',
      },
      borderWidth: {
        pico: 'var(--border-width-pico)',
        nano: 'var(--border-width-nano)',
      },
      fontSize: {
        h5: ['var(--font-size-h5)', 'var(--line-height-h5)'],
        h4: ['var(--font-size-h4)', 'var(--line-height-h4)'],
        h3: ['var(--font-size-h3)', 'var(--line-height-h3)'],
        h2: ['var(--font-size-h2)', 'var(--line-height-h2)'],
        h1: ['var(--font-size-h1)', 'var(--line-height-h1)'],
        base: ['var(--font-size-base)', 'var(--line-height-base)'],
        sub: ['var(--font-size-sub)', 'var(--line-height-sub)'],
        label: ['var(--font-size-label)', 'var(--line-height-label)'],
        micro: 'var(--font-size-micro)',
        mili: 'var(--font-size-mili)',
        centi: 'var(--font-size-centi)',
        deca: 'var(--font-size-deca)',
        kilo: 'var(--font-size-kilo)',
        mega: 'var(--font-size-mega)',
      },
      boxShadow: {
        default: 'var(--box-shadow-default)',
      },
      borderColor: {
        'success-light': 'var(--border-color-success-light)',
      },
      fontFamily: {
        sans: 'var(--font-family-sans)',
        mono: 'var(--font-family-mono)',
      },
      textColor: {
        light: 'var(--text-color-light)',
        medium: 'var(--text-color-medium)',
        dark: 'var(--text-color-dark)',
        orange: 'var(--text-color-orange)',
      },
      zIndex: {
        default: 'var(--z-index-default)',
        absolute: 'var(--z-index-absolute)',
        select: 'var(--z-index-select)',
        input: 'var(--z-index-input)',
        popover: 'var(--z-index-popover)',
        tooltip: 'var(--z-index-tooltip)',
        header: 'var(--z-index-header)',
        backdrop: 'var(--z-index-backdrop)',
        drawer: 'var(--z-index-drawer)',
        sidebar: 'var(--z-index-sidebar)',
        modal: 'var(--z-index-modal)',
      },
    },
  },
};
