export default {
  input: './src/index.ts',
  output: {
    dir: 'dist/esm',
    format: 'esm',
    preserveModules: true,
    preserveModulesRoot: 'src',
    sourcemap: false,
  },
  external: [
    /^react(\/|$)/,
    /^react-dom(\/|$)/,
    /^react-icons(\/|$)/,
    /^country-flag-icons(\/|$)/,
    /^embla-carousel/,
    '@tecsinapse/cortex-core',
    'clsx',
    'currency.js',
    'react-stately',
    'react-aria',
    'sonner',
    '@floating-ui/react',
    '@internationalized/date',
    'react-spring',
    'react-dropzone',
    'react-imask',
    'react-international-phone',
    'uuid',
    'tailwind-variants',
  ],
};
