name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: install and prepare
        run: yarn

      - name: lint
        run: yarn lint:fix

      - name: cache
        uses: actions/cache@v3
        id: ci-action-cache
        with:
          path: ./*
          key: ${{ github.sha }}

  build:
    runs-on: ubuntu-latest
    needs: lint
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore
        uses: actions/cache@v3
        id: ci-action-cache
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: build docs
        run: yarn build:storybook
