name: update develop

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup user
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: update develop
        run: |
          git checkout master
          git fetch origin
          git checkout develop
          git pull
          git merge origin/master
          git push origin develop
